version: '3.8'

services:
  spark-master:
    container_name: da-spark-master
    build: .
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    environment:
      - SPARK_MASTER_HOST=da-spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_LOG_DIR=/opt/spark/spark-events
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - '9090:8080'  # Master Web UI
      - '7077:7077'  # Spark Master port
    networks:
      - spark-network

  spark-history-server:
    container_name: da-spark-history
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/spark-events
      - SPARK_HISTORY_UI_PORT=18080
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'  # History Server UI
    networks:
      - spark-network

  spark-worker:
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    environment:
      - SPARK_MASTER=spark://da-spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_DIR=/opt/spark/work
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./data:/opt/spark/data
      - ./:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - '8081-8083:8081'  # Worker Web UI
    networks:
      - spark-network

volumes:
  spark-logs:

networks:
  spark-network:
    driver: bridge
