version: '3.9'

services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./:/opt/spark/apps
    command: ["bash", "-c", "mkdir -p /data && /usr/local/bin/spark-minio-entrypoint.sh"]
    networks:
      spark-net:
        ipv4_address: 192.168.1.100
    ports:
      - "8080:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master RPC

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://192.168.1.100:7077
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./:/opt/spark/apps
    command: ["bash", "-c", "mkdir -p /data && /usr/local/bin/spark-minio-entrypoint.sh"]
    networks:
      spark-net:
        ipv4_address: 192.168.1.101
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console

networks:
  spark-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
